### ISSUE TITLE
How we Slack

### ISSUE THREAD

**Issue by ghmlee** [cosmoshq/startup#130]
* https://medium.com/@wmorein/how-we-slack-at-fiftythree-5f6f8c4dcb1b

@blakepark @hanjaelee  Please comment about this.

**Comment by hanjaelee** [comment]
this idea is very good, but now, i think it isn't proper to our team if our slack channel is divided like this, because our slack channel will be mounting up, unnecessary slack channel can be created so i think that we need just some necessary channel

**Comment by blakepark** [comment]
@hanjaelee I partly agree.

But It seems like we need Channeling because lots of requests are coming in from the Github. We need to prepare for the possible problems in advance. I think it would be nice to use above rules.

**Comment by ghmlee** [comment]
@blakepark please give me your example. we can consider your opinion.
